runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: html/index.html
  upload: html/index.html
  secure: always

- url: /bio(.*)
  static_files: html/bio\1.html
  upload: html/bio(.*).html
  secure: always

- url: /cv
  script: html/cv.php
- url: /cv.ja
  script: html/cv.ja.php

- url: /photo/(.*)
  static_files: html/photo/\1
  upload: html/photo/(.*)
  secure: always

- url: /avatar.jpg
  static_files: html/avatar.jpg
  upload: html/avatar.jpg
  secure: always

- url: /style/(.*)
  static_files: html/style/\1
  upload: html/style/(.*)
  secure: always

- url: /skyline/(.*)
  static_files: html/skyline/\1
  upload: html/skyline/(.*)
  secure: always

- url: /psychsheet/ac-2018
  script: html/psychsheet/redirect.php
- url: /psychsheet/ac-2018.html
  script: html/psychsheet/redirect.php
